# -*- coding: utf-8 -*-
"""DAY_9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nvJFtGgKiN7KPdSTKaNn7eBg8aVB5Etk
"""

# Functions In Python
def hello():
    print("Mian Shakar Afzal")
hello()

# 1 parameter
def greet(name):
    print("Hello", name)
greet("Mian")

# 2 Parameter
def add(a, b):
    print(a + b)
add(10, 20)

def add(a, b):
    return a + b
result = add(10, 20)
print(result)

# Default Parameters
def greet(name="Guest"):
    print("Hello", name)
greet()
greet("Ali")

# Keyword Arguments
def student(name, age):
    print(name, age)
student(age=22, name="Mian")

# Positional Arguments
def info(name, city):
    print(name)
    print(city)
info("Ali", "Islamabad")

# *args
def total(*numbers):
    print(numbers)
total(10,20,30)

def total(*numbers):
    s = 0
    for i in numbers:
        s += i
    print(s)
total(10,20,30,40)

# Keyword Variable Arguments (**kwargs)
def person(**data):
    print(data)
person(name="Mian", age=22, city="Dinga")

# Nested Functions
def outer():
    print("Outer")
    def inner():
        print("Inner")
    inner()
outer()

# Lambda Function (Anonymous Function)
def square(x):
    return x*x
print(square(5))

square = lambda x: x*x
print(square(5))

add = lambda a,b: a+b
print(add(10,20))

largest = lambda a,b,c: max(a,b,c)
print(largest(10,50,20))

# map()
numbers = [1,2,3,4,5]
result = map(lambda x:x*x, numbers)
print(list(result))

# Upper Case
names = ["ali","mian","ahmad"]
result = map(str.upper, names)
print(list(result))

# filter()
numbers = [1,2,3,4,5,6]
even = filter(lambda x:x%2==0, numbers)
print(list(even))

numbers = [1,2,3,4,5,6]
odd = filter(lambda x:x%2!=0, numbers)
print(list(odd))

# Names Longer Than 4 Letters
names = ["Ali","Ahmad","Mian","Shakar"]
result = filter(lambda x:len(x)>4, names)
print(list(result))

# reduce()
from functools import reduce
numbers = [1,2,3,4]
result = reduce(lambda x,y:x*y, numbers)
print(result)

# Sum All Numbers
from functools import reduce
numbers = [10,20,30,40]
result = reduce(lambda x,y:x+y, numbers)
print(result)

from functools import reduce
numbers = [1,2,3,4,5]

# Square all numbers
squares = list(map(lambda x:x*x, numbers))

# Keep even squares
evens = list(filter(lambda x:x%2==0, squares))

# Sum even squares
answer = reduce(lambda x,y:x+y, evens)

print("Squares :", squares)
print("Even Squares :", evens)
print("Final Sum :", answer)