# -*- coding: utf-8 -*-
"""DAY_7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qxTr2x8YgYNJIwi5oOe5i5WLjf--3YHS
"""

# Creating empty dictionary
d = {}
print(d)
# 1D dictionary
d1 = { 'Name' : 'Mian' ,'Gender' : 'Male' }
print(d1)
# with mixed keys
d2 = {(1,2,3):1,'hello':'world'}
print(d2)
# 2D dictionary -> JSON
s = {
    'name':'Mian',
     'college':'PGC',
     'subjects':{
         'Physics':80,
         'maths':90,
         'english':85
     }
}
print(s)
# using sequence and dict function
d4 = dict([('Name','Mian'),('age',22),(3,3)])
print(d4)
# duplicate keys
d5 = {'name':'','name':''}
print(d5)
# mutable items as keys
d6 = {'name':'nitish',(1,2,3):2}
print(d6)

# Accessing Items
my_dict = {'name': 'Mian', 'age': 22}
# []
my_dict['age']
# get
my_dict.get('age')
s['subjects']['maths']

d4['gender'] = 'male'
print(d4)
d4['weight'] = 78
print(d4)
s['subjects']['ds'] = 82
print(s)