# -*- coding: utf-8 -*-
"""DAY # 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oF9Httg3Rw8278GLmPuwiErmYuu4un7Y
"""

# Arithmetic Operators
a= int(input("Enter first Number:"))
b= int(input("Enter Second Number:"))
print("Sum:",a+b)
print("Diff:",a-b)
print("Multi:",a*b)
print("Div:",a/b)
print("Modulus:",a%b)
print("Floor Div:",a//b)
print("Exponent:",a**b)

# Comparison (Relational) Operators
a= int(input("Enter first Number:"))
b= int(input("Enter Second Number:"))
print(a == b)
print(a != b)
print(a > b)
print(a < b)
print(a >= b)
print(a <= b)

# Bitwise Operators
a = 5
b = 3
print(a & b)
print(a | b)
print(a ^ b)
print(~a)
print(a << 1)  # Left Shift
print(a >> 1)  # Right Shift

# Assignment Operators
x = 10
x += 5
print(x)
x -= 2
print(x)
x *= 2
print(x)
x /= 2
print(x)

# Logical Operators
a= int(input("Enter first Number:"))
b= int(input("Enter Second Number:"))
print(a > b and b > 0)
print(a < b or b > 0)
print(not(a > b))

# Membership Operators
fruits = ["apple", "banana", "mango"]
print("apple" in fruits)
print("orange" in fruits)
print("orange" not in fruits)

# IF ELSE STATMENT
email=input("ENTER EMAIL:")
passward=int(input("ENTER PASSWARD:"))
if email=="mian@gmail.com" and passward==12345:
   print("LOGIN SUCCESSFULLY")
else:
     print("INVALID LOGIN")

# Nested IF ELSE Statement
email = input("ENTER EMAIL: ")
password = int(input("ENTER PASSWORD: "))

if email == "mian@gmail.com" and password == 12345:
    print("LOGIN SUCCESSFULLY")

    if email == "mian@gmail.com" or password == 12345:
        print("Make sure Both Email & Password are Correct")
else:
    print("INVALID LOGIN")